development:
  adapter: postgresql
  database: simplesigndb_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: simplesigndb_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: simplesigndb_prod
  pool: 5
  timeout: 5000
  